<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_hello</name>
   <tag></tag>
   <elementGuidId>0d0e376f-fade-4400-9c6b-1a924f894c76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='P6b7dfb2ee78347f0ad24cd48ca2bb9fa_3_oReportCell']/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr[2]/td[3]/table/tbody/tr[3]/td[3]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'hello' or . = 'hello')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>A86d6be475b8e4fd1bdf6d9a1d4ad2bf753</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>hello</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6b7dfb2ee78347f0ad24cd48ca2bb9fa_3_oReportCell&quot;)/table[1]/tbody[1]/tr[2]/td[@class=&quot;A86d6be475b8e4fd1bdf6d9a1d4ad2bf7309xBc&quot;]/table[@class=&quot;A86d6be475b8e4fd1bdf6d9a1d4ad2bf7309xB&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;P6b7dfb2ee78347f0ad24cd48ca2bb9fa_3_r10&quot;]/tbody[1]/tr[2]/td[3]/table[@class=&quot;A86d6be475b8e4fd1bdf6d9a1d4ad2bf7132&quot;]/tbody[1]/tr[3]/td[@class=&quot;A86d6be475b8e4fd1bdf6d9a1d4ad2bf753cl&quot;]/div[@class=&quot;A86d6be475b8e4fd1bdf6d9a1d4ad2bf753&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//td[@id='P6b7dfb2ee78347f0ad24cd48ca2bb9fa_3_oReportCell']/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr[2]/td[3]/table/tbody/tr[3]/td[3]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('PA', &quot;'&quot;, 's Name')])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jo-123456'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EV Holder'])[2]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/preceding::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//tr[3]/td[3]/div</value>
   </webElementXpaths>
</WebElementEntity>
