<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>2d2b227d-b453-4b1e-8938-ede72a17f053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='P74a0593b42194db99551309c89e95fc3_1_oReportCell']/table/tbody/tr/td/div/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>this.fitproportional=true;this.pv=0;this.ph=0;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>95</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>644</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/EVS_STG/Reserved.ReportViewerWebControl.axd?ReportSession=u5lxus55vonana553mjyxgf0&amp;Culture=2057&amp;CultureOverrides=True&amp;UICulture=2057&amp;UICultureOverrides=True&amp;ReportStack=1&amp;ControlID=74a0593b42194db99551309c89e95fc3&amp;OpType=ReportImage&amp;IterationId=ff64cbe85b254c8a84f7095ea0735dbb&amp;StreamID=c8885841-f202-47a6-aab7-14c8cab5dafd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P74a0593b42194db99551309c89e95fc3_1_oReportCell&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;A51e4d0f6c90e47fca3394d2d3828324e13c&quot;]/div[@class=&quot;A51e4d0f6c90e47fca3394d2d3828324e13&quot;]/table[@class=&quot;P74a0593b42194db99551309c89e95fc3_1_r10&quot;]/tbody[1]/tr[2]/td[3]/div[1]/div[@class=&quot;A51e4d0f6c90e47fca3394d2d3828324e5&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//td[@id='P74a0593b42194db99551309c89e95fc3_1_oReportCell']/table/tbody/tr/td/div/table/tbody/tr[2]/td[3]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Word'])[1]/following::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIFF file'])[1]/following::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employment Verification Report'])[1]/preceding::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proof of Eligibility'])[1]/preceding::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//td[3]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
